### ISSUE TITLE
prev button not working

### ISSUE THREAD

**Issue by Abolfazl74** [brunnopleffken/enchanter#1]
this.callbacks.onPrevious is not a function

**Comment by weber-s** [comment]
Hello!
Thanks for this nice little wizard!

I have the same issue, for both the onNext and onPrevious.

After some investigation, it seems that the code is checking for `onNext() != null`, but it should be `onNext != null`. Same for `onPrevious() != null` that should read `onPrevious != null`.

I don't know TypeScript, so I just update the js code in my application, and it works.

**Comment by brunnopleffken** [comment]
Hello @weber-s 
Oops, indeed. My bad! 😅
It worked like a charm. I already commited this fix.
Thank you for your suggestion.
